name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/rectangle-58.png
    - assets/page-1/images/whatsapp-image-2023-05-22-at-531-1.png
    - assets/page-1/images/saly-16.png
    - assets/page-1/images/mapsicle-map-bg.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-N1L.png
    - assets/page-1/images/auto-group-yfg9.png
    - assets/page-1/images/vector-ajQ.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/cancel-icon.png
    - assets/page-1/images/rectangle-60.png
    - assets/page-1/images/vector-Bmx.png
    - assets/page-1/images/vector-29.png
    - assets/page-1/images/group-1431.png
    - assets/page-1/images/vector-hzW.png
    - assets/page-1/images/vector-S4v.png
    - assets/page-1/images/auto-group-tuah.png
    - assets/page-1/images/alert-background.png
    - assets/page-1/images/saly-16-c94.png
    - assets/page-1/images/card.png
    - assets/page-1/images/vector-Lei.png
    - assets/page-1/images/rectangle-4.png
    - assets/page-1/images/delete.png
    - assets/page-1/images/vector-XRg.png
    - assets/page-1/images/vector-t1L.png
    - assets/page-1/images/saly-16-pNA.png
    - assets/page-1/images/rectangle-57.png
    - assets/page-1/images/ellipse-22.png
    - assets/page-1/images/anolog-clock.png
    - assets/page-1/images/card-Y6a.png
    - assets/page-1/images/card-Ydk.png
    - assets/page-1/images/saly-16-omx.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/ellipse-22-bBU.png
    - assets/page-1/images/vector-28.png
    - assets/page-1/images/saly-16-tRU.png
    - assets/page-1/images/saly-16-SC6.png
    - assets/page-1/images/rectangle-3.png
    - assets/page-1/images/vector-TNn.png
    - assets/page-1/images/rectangle-60-MUA.png
    - assets/page-1/images/iconly-light-search.png
    - assets/page-1/images/rectangle-5.png
    - assets/page-1/images/front-shapes.png
    - assets/page-1/images/front-shapes-dga.png
    - assets/page-1/images/front-shapes-o5G.png
    - assets/page-1/images/front-shapes-ZaE.png
    - assets/page-1/images/front-shapes-USJ.png
    - assets/page-1/images/front-shapes-RMY.png
    - assets/page-1/images/front-shapes-VU2.png
    - assets/page-1/images/background.png
    - assets/page-1/images/front-shapes-fok.png
    - assets/page-1/images/card-PDx.png
    - assets/page-1/images/background-bnn.png
    - assets/page-1/images/front-shapes-whY.png
    - assets/page-1/images/rectangle-6.png
    - assets/page-1/images/card-mDg.png
    - assets/page-1/images/card-TKC.png
    - assets/page-1/images/background-oRp.png
    - assets/page-1/images/front-shapes-dkr.png
    - assets/page-1/images/front-shapes-ggE.png
    - assets/page-1/images/background-4uc.png
    - assets/page-1/images/background-fkr.png
    - assets/page-1/images/front-shapes-cKG.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
